ALTER TABLE users
  ADD COLUMN IF NOT EXISTS notification_email BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS default_currency   TEXT    NOT NULL DEFAULT 'USD',
  ADD COLUMN IF NOT EXISTS timezone           TEXT    NOT NULL DEFAULT 'UTC';
